### ISSUE TITLE
libmozdata.wiki_parser.InvalidWiki: Column headers are wrong

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/libmozdata#220]
The following change in the schema of the release owners table broke the tests: https://wiki.mozilla.org/index.php?title=Release_Management%2FRelease_owners&type=revision&diff=1246108&oldid=1245710

```
======================================================================
ERROR: test_ro (test_release_owners.ReleaseOwnersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/libmozdata/libmozdata/release_owners.py", line 42, in get_owners
    parser.feed(html)
  File "/libmozdata/libmozdata/wiki_parser.py", line 87, in feed
    HTMLParser.feed(self, data)
  File "/usr/local/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/libmozdata/libmozdata/wiki_parser.py", line 112, in handle_endtag
    raise StopIteration()
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/libmozdata/tests/test_release_owners.py", line 12, in test_ro
    owners = ro.get_owners()
  File "/libmozdata/libmozdata/release_owners.py", line 54, in get_owners
    raise InvalidWiki("Column headers are wrong")
libmozdata.wiki_parser.InvalidWiki: Column headers are wrong
```

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid if you want I an delete the v0.2.1 tag and ahrd reset the tree prior to that "Release".

We could just ignore v0.2.1 since it wasn't pushed to PyPi. No need to delete the tag.
