### ISSUE TITLE
[BugzillaShorten] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/libmozdata#227]
The bug happens when having a very long URL (e.g., length > 8600)

```
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 764, in send_email
    title, body = self.get_email(date, data)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 710, in get_email
    query_url=utils.shorten_long_bz_url(self.query_url),
  File "/home/rm_bot/bugbot/bugbot/utils.py", line 202, in shorten_long_bz_url
    BugzillaShorten(url, url_data=data, url_handler=url_handler).wait()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 134, in wait
    r.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 121, in cb
    query.handler(response)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/bugzilla.py", line 1060, in __urls_cb
    self.url_handler.handle(res["url"])
TypeError: string indices must be integers
```

**Comment by suhaibmujahid** [comment]
For a long URL (~8600 characters), Bugzilla returns a 200 response with [HTML content](https://github.com/mozilla/libmozdata/files/11470085/bugzilla_html_response.txt) that redirects to https://bugzilla.mozilla.org/home. 

For longer URLs:
- `HTTPError: 414 Client Error: Request-URI Too Long for url`
- `HTTPError: 413 Client Error: Request Entity Too Large for url`
