### ISSUE TITLE
test_patchanalysis.py is failing

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozdata#99]
```
FAIL: test_bug_analysis (test_patchanalysis.PatchAnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/home/travis/build/mozilla/libmozdata/tests/test_patchanalysis.py", line 450, in test_bug_analysis
    self.assertEqual(info['landings']['esr'], datetime(2016, 4, 7, 18, 41, 3, tzinfo=pytz.UTC))
AssertionError: None != datetime.datetime(2016, 4, 7, 18, 41, 3, tzinfo=<UTC>)
```

**Comment by marco-c** [comment]
@La0 so it was a known failure, but I had forgotten about it.
Anyway, it was fixed in #112.
